include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
