name: moview
description: This app allows you to see the latest information about movies.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  fade_shimmer: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_state_notifier: ^0.7.1
  flutter_svg: ^1.0.1
  freezed_annotation:
  gap: ^2.0.0
  go_router: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  line_icons: ^2.0.1
  loading_animation_widget: ^1.0.0+1
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  responsive_grid_list: ^1.2.3
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.1.4
  pedantic_mono: ^1.15.0

flutter_icons:
  image_path: 'assets/icons/icon.png'
  android: true
  ios: true
  # adaptive_icon_foreground: 'assets/icons/icon.png'
  # adaptive_icon_background: '#000000'

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

# アイコン設定 ※設定時はandroid/app/build.gradleの「minSdkVersion flutter.minSdkVersion」を「minSdkVersion 16」にすること
# fvm flutter pub run flutter_launcher_icons:main

# fvm flutter packages pub run build_runner build