name: moview
description: This app allows you to see the latest information about movies.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.15.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - images/sample.jpeg

# fvm flutter packages pub run build_runner build